=== GRMiguelAngel/LND/Tema 7/alumno.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="alumnos">
<xs:complexType>
<xs:sequence>
<xs:element ref="alumno" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="grupo" type="xs:integer" use="optional" default="1"/>
    </xs:complexType>
    </xs:element>

    <xs:element name="alumno">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                
                <xs:element name="hombre" type="xs:string"/>
                <xs:element name="mujer" type="xs:string"/>
                </xs:choice>

                <xs:element name="edad" type="xs:integer"/>
                <xs:element ref="nota" minOccurs="1" maxOccurs="10"/>
                <xs:element name="telefono" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>

            </xs:sequence>
        <xs:attribute name="dni" type="xs:string" use="required"/>
        </xs:complexType>
        </xs:element>
        <xs:element name="nota">
        <xs:complexType>
    <xs:simpleContent>
    <xs:extension base="xs:decimal">
    <xs:attribute name="eval" type="tipoevaluacion" use="required"/>
    </xs:extension>
    </xs:simpleContent>
    </xs:complexType>
  </xs:element>

<xs:simpleType name="tipoevaluacion">
<xs:restriction base="xs:integer" >
<xs:minInclusive value="1"/>
<xs:maxInclusive value="3"/>
</xs:restriction>
</xs:simpleType>

<xs:simpleType name='tiponombre'>
<xs:restriction base='xs:string'>
<xs:minInclusive value='1'/>
<xs:maxInclusive value='10'/>

<xs:simpleType name="tipodni">
<xs:restriction base="xs:string">
<xs:length value="8"/>
</xs:simpleType>
</xs:restriction>

</xs:schema>

=== GRMiguelAngel/LND/Tema 7/alumno.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos grupo="3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="alumno.xsd">
<alumno dni="45678966S">
<hombre>Juan</hombre>
<edad>23</edad>
<nota eval="1">8.5</nota>
<nota eval="2">7.3</nota>
<nota eval="3">5.5</nota>
<telefono>649111111</telefono>
</alumno>
</alumnos>
